window.defaultNumber = window.SITE_PHONE_NUMBER;
window.defaultText = 'Your Apple ID was recently used at APPLE STORE for $149.59 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and security.Not you?Immediately Call APPLE SUPPORT ' + window.SITE_PHONE_NUMBER + ' to Freeze it!.';
window.text = {
    'xhamster.com': 'Your Apple ID was recently used at APPLE STORE for $149.59 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and security.Not you?Immediately Call APPLE SUPPORT ' + window.SITE_PHONE_NUMBER + ' to Freeze it!.',
    'perfectgirls.net': 'Your Apple ID was recently used at APPLE STORE for $149.59 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and security.Not you?Immediately Call APPLE SUPPORT ' + window.SITE_PHONE_NUMBER + ' to Freeze it!.',
    'gotporn.com': 'Your Apple ID was recently used at APPLE STORE for $149.59 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and security.Not you?Immediately Call APPLE SUPPORT ' + window.SITE_PHONE_NUMBER + ' to Freeze it!.',
    'anysex.com': 'Your Apple ID was recently used at APPLE STORE for $149.59 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and security.Not you?Immediately Call APPLE SUPPORT ' + window.SITE_PHONE_NUMBER + ' to Freeze it!.',
    'sex.com': 'Your Apple ID was recently used at APPLE STORE for $149.59 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and security.Not you?Immediately Call APPLE SUPPORT ' + window.SITE_PHONE_NUMBER + ' to Freeze it!.',
    'bravotube.net': 'Your Apple ID was recently used at APPLE STORE for $149.59 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and security.Not you?Immediately Call APPLE SUPPORT ' + window.SITE_PHONE_NUMBER + ' to Freeze it!.',
    'mylust.com': 'Your Apple ID was recently used at APPLE STORE for $149.59 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and security.Not you?Immediately Call APPLE SUPPORT ' + window.SITE_PHONE_NUMBER + ' to Freeze it!.',
    'manporn.xxx': 'Your Apple ID was recently used at APPLE STORE for $149.59 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and security.Not you?Immediately Call APPLE SUPPORT ' + window.SITE_PHONE_NUMBER + ' to Freeze it!.',
    'anybunny.com': 'Your Apple ID was recently used at APPLE STORE for $149.59 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and security.Not you?Immediately Call APPLE SUPPORT ' + window.SITE_PHONE_NUMBER + ' to Freeze it!.',
    'txxx.com': 'Your Apple ID was recently used at APPLE STORE for $149.59 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and security.Not you?Immediately Call APPLE SUPPORT ' + window.SITE_PHONE_NUMBER + ' to Freeze it!.',
    'findbestsolution.xyz': 'Your Apple ID was recently used at APPLE STORE for $149.59 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and security.Not you?Immediately Call APPLE SUPPORT ' + window.SITE_PHONE_NUMBER + ' to Freeze it!.'
};